# Generated by Django 5.2.3 on 2025-11-14 11:26

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teseapi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="embedding",
            field=pgvector.django.vector.VectorField(blank=True, null=True),
        ),
    ]
