# Generated by Django 5.2.3 on 2025-11-14 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0002_alter_conversation_product"),
        ("products", "0001_initial"),
        ("teseapi", "0002_listing_embedding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="listing",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.listing",
            ),
        ),
        migrations.RemoveField(
            model_name="listingimage",
            name="content_type",
        ),
        migrations.DeleteModel(
            name="Listing",
        ),
        migrations.DeleteModel(
            name="ListingImage",
        ),
    ]
