# Generated by Django 5.2.3 on 2025-11-14 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teseapi", "0003_alter_cartitem_listing_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="order",
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
