# Generated by Django 5.2.3 on 2025-11-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APILog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.CharField(max_length=255)),
                ("method", models.CharField(max_length=10)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("request_body", models.TextField(blank=True, null=True)),
                ("status_code", models.IntegerField()),
                ("response_body", models.TextField(blank=True, null=True)),
                (
                    "execution_time",
                    models.FloatField(help_text="Time taken in seconds"),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
