# Generated by Django 5.2.3 on 2025-11-12 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("search", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="querylog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="searchindexentry",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddIndex(
            model_name="searchindexentry",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="search_sear_content_66c3da_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="searchindexentry",
            unique_together={("content_type", "object_id")},
        ),
    ]
