# Generated by Django 5.2.3 on 2025-11-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_listing_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="organic",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
